"""Filters that keep correlation output load-test-relevant.

Browser fingerprint headers and client cache-busters change between headed
vs headless runs and across requests, but they are not extract→pass work for
k6/JMeter. Session cookies, CSRF/auth headers, and body/query tokens are.
"""
from __future__ import annotations

import re
from typing import Any, Dict, Optional
from urllib.parse import urlparse

# Headers that tools auto-manage or that are client fingerprints — never correlate.
BROWSER_NOISE_REQUEST_HEADERS = frozenset({
    "accept",
    "accept-encoding",
    "accept-language",
    "cache-control",
    "connection",
    "content-length",
    "content-type",
    "cookie",  # handled as cookie jar / per-cookie location
    "dnt",
    "host",
    "origin",
    "pragma",
    "priority",
    "referer",
    "sec-ch-ua",
    "sec-ch-ua-mobile",
    "sec-ch-ua-platform",
    "sec-fetch-dest",
    "sec-fetch-mode",
    "sec-fetch-site",
    "sec-fetch-user",
    "upgrade-insecure-requests",
    "user-agent",
})

# Only these request-header classes belong in extract→pass scripts.
CORRELATABLE_REQUEST_HEADER_EXACT = frozenset({
    "authorization",
    "proxy-authorization",
    "x-csrf-token",
    "x-xsrf-token",
    "x-csrf",
    "x-xsrf",
    "requestverificationtoken",
    "x-auth-token",
    "x-access-token",
    "x-api-token",
    "authentication",
})

CORRELATABLE_REQUEST_HEADER_RE = re.compile(
    r"(csrf|xsrf|authorization|auth[-_]?token|access[-_]?token|"
    r"bearer|requestverification|anti[-_]?forgery)",
    re.IGNORECASE,
)

# Query keys generated by the client (not extracted from a prior response).
CLIENT_SIDE_QUERY_KEYS = frozenset({
    "_",
    "t",
    "ts",
    "timestamp",
    "currenttime",
    "cachebust",
    "cachebuster",
    "nocache",
    "rnd",
    "random",
    "cb",
    "_t",
    "_ts",
})

# Query keys that usually carry tester-supplied search/filter data (parameters).
PARAMETERISH_QUERY_KEYS = frozenset({
    "name",
    "nameorid",
    "nameid",
    "search",
    "q",
    "query",
    "keyword",
    "username",
    "email",
    "employee",
    "employeename",
    "empnumber",
    "remarks",
    "comment",
    "amount",
    "fromdate",
    "todate",
})

# Responses that often contain dictionary words coinciding with form input.
STATIC_RESPONSE_URL_HINTS = (
    "/i18n/",
    "/locale/",
    "/messages",
    "/translation",
    "/lang/",
    "/assets/",
    ".js",
    ".css",
    "fonts.",
)

LOGIN_FIELD_SELECTOR_RE = re.compile(
    r"""(?:name|id)\s*=\s*["']?(username|user|password|passwd|email|login)\b"""
    r"""|\[type\s*=\s*["']?password["']?\]""",
    re.IGNORECASE,
)


def is_noise_request_header(header_name: str) -> bool:
    """Return True for browser fingerprint / transport headers."""
    key = (header_name or "").strip().lower()
    if not key:
        return True
    if key in BROWSER_NOISE_REQUEST_HEADERS:
        return True
    if key.startswith("sec-ch-") or key.startswith("sec-fetch-"):
        return True
    return False


def is_correlatable_request_header(header_name: str) -> bool:
    """Return True only for auth/CSRF-style request headers worth scripting."""
    key = (header_name or "").strip().lower()
    if not key or is_noise_request_header(key):
        return False
    if key in CORRELATABLE_REQUEST_HEADER_EXACT:
        return True
    return bool(CORRELATABLE_REQUEST_HEADER_RE.search(key))


def is_client_side_query_key(key: str) -> bool:
    """Return True for cache-buster / client timestamp query parameters."""
    return (key or "").strip().lower() in CLIENT_SIDE_QUERY_KEYS


def is_parameterish_query_key(key: str) -> bool:
    """Return True when a query key is typically tester-supplied data."""
    return (key or "").strip().lower() in PARAMETERISH_QUERY_KEYS


def is_static_asset_url(url: str) -> bool:
    """Return True for i18n/static URLs that should not seed fill correlations."""
    lower = (url or "").lower()
    return any(hint in lower for hint in STATIC_RESPONSE_URL_HINTS)


def is_login_field_selector(selector: str) -> bool:
    """Return True for username/password/email style form fields."""
    return bool(LOGIN_FIELD_SELECTOR_RE.search(selector or ""))


def _location_header_name(location: str) -> Optional[str]:
    """Extract header name from ``header.X`` / ``header.set-cookie.Y`` locations."""
    loc = (location or "").strip()
    if not loc.lower().startswith("header."):
        return None
    rest = loc.split(".", 1)[1]
    if rest.lower().startswith("set-cookie"):
        return None  # cookie handling is separate and valid
    return rest.split(".", 1)[0]


def is_noise_location(location: str) -> bool:
    """Return True when a source/target location is browser-header noise."""
    name = _location_header_name(location or "")
    if name is None:
        # Also catch ``header.User-Agent`` style already normalized
        lower = (location or "").lower()
        if lower.startswith("header."):
            raw = lower[7:].split(".", 1)[0]
            return is_noise_request_header(raw)
        return False
    return is_noise_request_header(name)


def is_actionable_dependency(dep: Dict[str, Any]) -> bool:
    """Keep only dependencies a performance engineer would script.

    Drops shared User-Agent chains, referer noise, and low-value shared_value
    links between identical browser headers.
    """
    if not dep:
        return False
    source_loc = str(dep.get("source_location") or "")
    target_loc = str(dep.get("target_location") or "")
    if is_noise_location(source_loc) or is_noise_location(target_loc):
        return False

    # Raw-body containment of short digits is almost always false-positive noise
    # (e.g. "22" inside HTML/JSON matching path.empNumber pages).
    src_l = source_loc.lower()
    val = str(dep.get("run1_value") or "")
    if src_l in ("body.raw", "body.raw_body") or src_l.endswith(".raw"):
        if val.isdigit() and len(val) < 6:
            return False
        if len(val) < 8:
            return False

    # Path targets need the literal as a full path segment on the target URL.
    if target_loc.lower().startswith("path.") and val.isdigit():
        tgt_url = str(dep.get("target_request") or "")
        segs = [s for s in urlparse(tgt_url).path.split("/") if s]
        if val not in segs:
            return False
        # Prefer API resource parents over soft PIM page paths
        try:
            idx = segs.index(val)
            prev = segs[idx - 1].lower() if idx > 0 else ""
        except ValueError:
            prev = ""
        api_parents = {
            "employees",
            "employee",
            "requests",
            "request",
            "claims",
            "claim",
            "users",
            "user",
            "orders",
            "order",
            "id",
        }
        if prev and prev not in api_parents and not prev.endswith("id"):
            # Allow empNumber only on /api/ URLs
            if prev == "empnumber" and "/api/" not in tgt_url.lower():
                return False

    ctype = (dep.get("correlation_type") or "").lower()
    # shared_value that only copies the same header key across requests is noise
    if ctype == "shared_value":
        src_h = _location_header_name(source_loc)
        tgt_h = _location_header_name(target_loc)
        if src_h and tgt_h and src_h.lower() == tgt_h.lower():
            if not is_correlatable_request_header(src_h):
                return False

    value_key = str(dep.get("value_key") or "").lower()
    if value_key in ("user_agent", "sec_ch_ua", "referer", "accept", "content_length"):
        return False

    return True


def is_actionable_correlation(corr: Dict[str, Any]) -> bool:
    """Keep dynamic candidates that matter for scripting."""
    if not corr:
        return False
    location = str(corr.get("location") or "").lower()
    key = str(corr.get("key") or "")
    name = str(corr.get("dynamic_name") or "").lower()

    if location == "header" and not is_correlatable_request_header(key):
        return False
    if location == "query" and is_client_side_query_key(key):
        return False
    if location == "query" and is_parameterish_query_key(key):
        return False
    if name in ("user_agent", "sec_ch_ua", "referer", "currenttime"):
        return False
    # path IDs are actionable when present
    if location == "path":
        return True
    return True
